expense_tracking/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView
from rest_framework import routers
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)


router = routers.DefaultRouter()
router.register('expense_types', views.ExpenseTypeView)

app_name = "expense_tracking"

urlpatterns = [
    path('', views.index, name="index"),
    path('expenses', views.expenses, name="expenses"),
    path('add/', views.add_expense, name="add_expense"),
    path('edit/<int:id>', views.edit_expense, name="edit_expense"),
    path("filter/<int:id>/", views.filter, name='filter'),
    path(
        "get_data/",
        views.get_data,
        name='get_data'
    ),
    path(
        "results/",
        views.results,
        name='results'
    ),
    path(
        "delete_expense/<int:id>",
        views.delete_expense,
        name='delete_expense'
    ),
    path("login/", views.login_request, name="login_request"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path('api/v1/', include(router.urls)),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('expense_tracking:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy(
                'expense_tracking:password_reset_complete'
            )
        ),
        name='password_reset_confirm'),
    path(
        "accounts/password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense_tracking.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

templates/accounts/password_reset.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %} Password Reset {% endblock %}
{% block body %}
<div class="page-content">
  <legend class="border-bottom mb-4">
    Password Reset
  </legend>
  <p>Forgotten your password?  Enter your email address below, and we'll email instructions for setting a new one.</p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button class="btn btn-sm btn-primary" type="submit">Reset My Password</button>
  </form>
</di>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block body %}
<div class="page-content">
<legend class="border-bottom mb-4">
   Password Reset Complete
</legend>
  <p>Your password has been set. You may go ahead and log in now</p>
   <a href="{% url 'expense_tracking:login_request' %}">Login</a>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block body %}
<div class="page-content">
  {% if validlink %}
  <legend class="border-bottom mb-4">
     Reset Password
  </legend>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-sm btn-primary" type="submit">Reset Password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
</div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Email Sent{% endblock %}
{% block body %}
<div class="page-content">
  <legend class="border-bottom mb-4">
     Password Sent
  </legend>
  	<div>
		    <p>
            An email has been sent with instructions to reset your password.
        </p>
	</div>
</div>
{% endblock %}