expense_tracking/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth.views import LogoutView
from rest_framework import routers
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView)


router = routers.DefaultRouter()
router.register('expense_types', views.ExpenseTypeView)

app_name = "expense_tracking"

urlpatterns = [
    path('', views.index, name="index"),
    path('expenses', views.expenses, name="expenses"),
    path('add/', views.add_expense, name="add_expense"),
    path('edit/<int:id>', views.edit_expense, name="edit_expense"),
    path("filter/<int:id>/", views.filter, name='filter'),
    path(
        "get_data/",
        views.get_data,
        name='get_data'
    ),
    path(
        "results/",
        views.results,
        name='results'
    ),
    path(
        "delete_expense/<int:id>",
        views.delete_expense,
        name='delete_expense'
    ),
    path("login/", views.login_request, name="login_request"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path('api/v1/', include(router.urls)),
    path(
        "accounts/password-reset/",
        PasswordResetView.as_view(
            template_name='accounts/password_reset.html',
            success_url=reverse_lazy('expense_tracking:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        "accounts/password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy(
                'expense_tracking:password_reset_complete'
            )
        ),
        name='password_reset_confirm'),
    path(
        "accounts/password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expense_tracking.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

expense_tracking/models.py
from django.db import models
from django.utils import timezone


class ExpenseType(models.Model):
    # Class for expense type

    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        # String method returns expense type name

        return self.name


class Expense(models.Model):
    # Class for expense

    expense_date = models.DateField()
    expense_type = models.ForeignKey(
        ExpenseType,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    org = models.CharField(max_length=200)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    notes = models.CharField(max_length=200, blank=True)
    inserted_date = models.DateTimeField(
        default=timezone.now
    )

    def __str__(self):
        # String method returns expense name and date

        return self.name + '_' + self.expense_date.strftime('%m_%d_%Y')

expense_tracking/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Expense
from django.core.exceptions import ValidationError
from captcha.fields import ReCaptchaField


class AuthenticationFormWithCaptchaField(AuthenticationForm):
    # Class for authentication form, includingg recaptcha field
    captcha = ReCaptchaField(
         public_key='6LdjEmIfAAAAALZW2a9z9UpLgBp32VM_0b_Nuico',
         private_key='6LdjEmIfAAAAALrOo-NCsc4ZmpDqU5zhG--jMMnA',
    )


class ExpenseForm(forms.ModelForm):
    # Class for expense form

    class Meta:
        model = Expense
        fields = (
            'expense_date',
            'expense_type',
            'name',
            'org',
            'amount',
            'notes'
        )

    def clean_expense_date(self):
        # Function to check if expense date is not populated

        expense_date = self.cleaned_data['expense_date']
        if expense_date is None:
            raise ValidationError('Please select an expense date.')
        return expense_date

    def clean_expense_type(self):
        # Function to check if expense type is not selected

        expense_type = self.cleaned_data['expense_type']
        if expense_type is None:
            raise ValidationError('Please enter an expense type.')
        return expense_type

    def clean_name(self):
        # Function to check if expense name is not populated

        name = self.cleaned_data['name']
        if name is None:
            raise ValidationError('Please enter a name.')
        return name

    def clean_org(self):
        # Function to check if expense organization is not populated

        org = self.cleaned_data['org']
        if org is None:
            raise ValidationError('Please enter a org.')
        return org

    def clean_amount(self):
        # Function to check if expense amount is not populated

        amount = self.cleaned_data['amount']
        if amount is None:
            raise ValidationError('Please enter a amount.')
        return amount

    def save(self, commit=True):
        # Funtion to save expense form data

        expense = super(ExpenseForm, self).save(commit=False)
        expense.expense_date = self.cleaned_data['expense_date']
        expense.expense_type = self.cleaned_data['expense_type']
        expense.name = self.cleaned_data['name']
        expense.org = self.cleaned_data['org']
        expense.amount = self.cleaned_data['amount']
        expense.notes = self.cleaned_data['notes']
        if commit:
            expense.save()
            return expense


class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

expense_tracking/views.py
from locale import currency
import pandas as pd
import pandasql as ps
import numpy as np
import plotly.graph_objs as go
import logging


from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Expense, ExpenseType
from .forms import (
    ExpenseForm,
    AuthenticationFormWithCaptchaField,
    DateRangeForm
)
from django.contrib.auth import (
    login, logout, authenticate)
from django.contrib import messages
from .signals import log_user_logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from rest_framework import viewsets
from .serializers import ExpenseTypeSerializer
from pretty_html_table import build_table
from django.utils import timezone
from plotly.offline import plot


# Set float values to 2 decimal places
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('future.no_silent_downcasting', True)

logger = logging.getLogger(__name__)

class ExpenseTypeView(viewsets.ModelViewSet):
    # Class for expense type view set

    # Select all expense types
    queryset = ExpenseType.objects.all().order_by('name')

    # Serialize class
    serializer_class = ExpenseTypeSerializer


def get_chart(category, title):

    df = category
    trace1 = go.Bar(
                x=df['Category'],
                y=df['Budget Amount'],
                name='Budget',
                hovertemplate='%{y}',  # Display only the value on hover
                #text=[f'{cat}: {val}' for cat, val in zip(budget['Category'], budget['Total Monthly Balance'])],
                textposition='auto',
                showlegend=True
            )

    trace2 = go.Bar(
        x=df['Category'],
        y=df['Monthly Expense Amount'],
        name='Expense',
        hovertemplate='%{y}',  # Display only the value on hover
        # text=[f'{cat}: {val}' for cat, val in zip(budget['Category'], budget['Monthly Expense Amount'])],
        textposition='auto',
        showlegend=True
    )

    layout = go.Layout(
        title={
            'text': f'<b>{title} Monthly Budget</b>',
        },
        title_x=.5,
        xaxis={
            'title': '<b>Category</b>'
        },
        yaxis={
            'title': '<b>Amount (in dollars)</b>'
        },
        barmode='group',
        height=500,  # Set the height of the chart in pixels
        plot_bgcolor='rgba(0, 0, 0, 0)',
        paper_bgcolor='rgba(0, 0, 0, 0)',
    )
    fig = go.Figure(data=[trace1, trace2], layout=layout)
    plt_div = plot(fig, output_type='div')
    return plt_div


def index(request):
    # Function renders landing page

    return render(
        request=request,
        template_name='expense_tracking/index.html',
    )


def login_request(request):
    # Function for handling login request

    # Verify the user is not logged into the application
    if not request.user.is_authenticated:

        # For user submitting the form
        if request.method == "POST":
            form = AuthenticationFormWithCaptchaField(
                request, data=request.POST
            )

            # If the form is valid, present user with a success alert
            # and redirect the the expense list
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                login(request, user)
                login_msg = f'{username} logged in successfully.'
                messages.success(
                    request,
                    login_msg
                )
                return redirect('expense_tracking:expenses')

            # Check if the users exist
            elif User.objects.filter(
                    username=form.cleaned_data.get('username')).exists():
                user = User.objects.filter(
                    username=form.cleaned_data.get('username')).values()

                # If the user's profile is inactive, alert the user to
                # contact the admin
                if(user[0]['is_active'] is False):
                    messages.info(
                        request,
                        'Contact the administrator to activate your account!'
                    )
                    return redirect('expense_tracking:login_request')

                # Present form to the user with any errors
                else:
                    return render(
                        request=request,
                        template_name='expense_tracking/login.html',
                        context={'form': form}
                    )

            # Present form to the user with any errors
            else:
                return render(
                    request=request,
                    template_name='expense_tracking/login.html',
                    context={'form': form}
                )

        # When the form is NOT being submitted, present to form to the user
        else:
            form = AuthenticationFormWithCaptchaField()
            return render(
                request=request,
                template_name='expense_tracking/login.html',
                context={'form': form}
            )

    # If the user is already logged into the application, provide alert
    # to inform the user and redirect her/him to the expenses list
    else:
        messages.info(
            request,
            '''You are already logged in.  You must log out to log in as
            another user.'''
        )

        # Redirect user to table of expense
        return redirect('expense_tracking:expenses')


def password_reset_complete(request):
    return render(
        request=request,
        template_name='accounts/password_reset_complete.html'
    )


@login_required()
def expenses(request):
    # Function requires user to be logged in and renders a table of expenses
    # showing the date, type organization, amount and notes (with edit and
    # delete buttons)

    # Set up pagination
    # Get 50 expenses per page, by expense date descending
    p = Paginator(Expense.objects.order_by(
        '-expense_date',
        'expense_type__name',
        'name',
        'org'
    ), 50)
    page = request.GET.get('page')
    my_expenses = p.get_page(page)

    distinct_expense_types = ExpenseType.objects.all().order_by(
            'name'
            )

    # Render expense table list 50 expense per page with page navigation at
    # the bottom of the page
    return render(request=request,
                  template_name='expense_tracking/expense.html',
                  context={
                      'my_expenses': my_expenses,
                      'distinct_expense_types': distinct_expense_types
                  }
                  )


@login_required()
def add_expense(request):
    # Function for adding an expense.  User must be logged in to access.

    # Obtain expense records ordered by expense name
    expense_types = ExpenseType.objects.order_by('name')

    # When the form method is post
    if request.method == 'POST':

        form = ExpenseForm(request.POST)

        # Check if form is valid
        if form.is_valid():

            # If form is valid, save values to database
            form.save()

            # Display successful alert message
            messages.success(
                request,
                'Expense added successfully.'
            )

            # Redirect user to table of expense
            return redirect('expense_tracking:expenses')

        # When form is invalid
        else:

            # Render the form, including drop down values for expense types
            # and display an form field errors at the top of the page in red
            return render(
                request=request,
                template_name='expense_tracking/add_expense.html',
                context={
                    'form': form,
                    'expense_types': expense_types
                }
            )

    # When the form method is get
    else:
        # Generate expense form
        form = ExpenseForm()

        # Render the form, including drop down values for expense types
        return render(
            request=request,
            template_name="expense_tracking/add_expense.html",
            context={
                'form': form,
                'expense_types': expense_types
            }
        )


@login_required
def edit_expense(request, id):
    # Function for adding an expense. User must be logged in to access.

    # Obtain expense record to edit by id
    expense_to_edit = Expense.objects.get(id=id)

    # Obtain list of expense types in order by name, except the selected value
    # by id from the form
    expense_types = ExpenseType.objects.exclude(
        id=expense_to_edit.expense_type.pk
    ).order_by('name')

    # When the form method is post
    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense_to_edit)

        # Check if form is valid
        if form.is_valid():

            # If form is valid, save changes to database
            form.save()

            # Display successful alert message
            messages.success(
                request,
                'Your expense was updated successfully!'
            )

        # Redirect user to table of expense
        return redirect('expense_tracking:expenses')

    # When the form method is get
    else:

        # Generate expense form with selected data from edit button selected
        form = ExpenseForm(instance=expense_to_edit)

        # Render the form with populated data, including drop down values
        # for expense types
        return render(
            request=request,
            template_name='expense_tracking/edit_expense.html',
            context={
                'expense_types': expense_types,
                'expense_to_edit': expense_to_edit,

templates/expense_tracking/add_expense.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Expenses{% endblock %}
{% block body %}
<div class="container">
  <main>
    <legend class="border-bottom mb-4">
        Add Expense
    </legend>
      <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <div class="row">
              <div class="col-sm-3">
                <label for="expense_date">Expense Date</label>
                <input
                    type="date"
                    class="form-control form-control-sm"
                    data-date-format="mm/dd/yyyy"
                    id="expense_date"
                    name="expense_date"
                    required="true"
                />
              </div>
              <div class="col-sm-6">
                <label for="expense_type">Expense Type</label>
                <select
                  class="form-control form-control-sm"
                  id="expense_type"
                  name="expense_type"
                >
                  <option
                    selected="true"
                    value='-1'
                    disabled
                  >
                    --- Select a Expense Type ---
                  </option>
                  {% for expense_type in expense_types %}
                    <option value="{{ expense_type.id }}">
                      {{ expense_type.name }}
                    </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-sm-3">
                <label for="amount">Amount</label>
                <input
                  type="number"
                  step='.01'
                  class="form-control form-control-sm"
                  id="amount"
                  required="true"
                  name="amount"
                  placeholder="Enter Amount"
                />
              </div>
          </div>
            <div class="row">
              <div class="col-sm-6">
                <label for="name">Expense</label>
                <input
                  type="text"
                  class="form-control form-control-sm"
                  id="name"
                  name="name"
                  required="true"
                  placeholder="Enter Expense"
                />
              </div>
              <div class="col-sm-6">
                <label for="org">Organization</label>
                <input
                  type="text"
                  class="form-control form-control-sm"
                  id="org"
                  name="org"
                  required="true"
                  placeholder="Enter Organization"
                />
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
              <label for="notes">Notes</label>
              <input
                type="text"
                class="form-control form-control-sm"
                id="notes"
                name="notes"
                placeholder="Enter Notes"
              />
            </div>
            </div>
          <br />
          <div class="row">
            <div class="col-sm-3">
              <button
                class="btn btn-sm btn-primary"
                id="send_btn"
                type="submit"
              >
                Add Expense
              </button>
              <button
                onclick="javascript:history.back();"
                class="btn btn-secondary btn-sm"
                type="submit"
              >
                Cancel
              </button>
            </div>
          </div>
      </form>
    </div>
  </main>
  </div>
{% endblock %}

templates/expense_tracking/budget.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Monthly Budget{% endblock %}
{%block body %}
<div class="container">
<main>
    <legend class="border-bottom mb4">
        {{current_month_display_name}} {{current_year}} Budget
    </legend>
        {% if none %}
            <p class="no_records">{{none}}</p>
        {% else %}
            {{ budget|safe }}
            <div class="row">
                {% for chart in charts %}
                <div class="col-sm-4">
                  <div class="card">
                    <div class="card-body">
                        {% autoescape off %}
                            {{ chart }}
                        {% endautoescape %}
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        {% endif %}
</main>
</div>
{% endblock %}

templates/expense_tracking/data_visualization.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Data{% endblock %}
{%block body %}
<div class="container">
<main>
    <legend class="border-bottom mb4">
        Expense Data
    </legend>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          <p>
              Select a start and end date to display your expenses within
              the specified range.
          </p>
          <div class="row">
            <div class="col-sm-3">
              <label for="start_date">Start Date</label>
              <input
                  type="date"
                  class="form-control form-control-sm"
                  data-date-format="mm/dd/yyyy"
                  id="start_date"
                  name="start_date"
                  required="false"
              />
            </div>
            <div class="col-sm-3">
              <label for="end_date">End Date</label>
              <input
                  type="date"
                  class="form-control form-control-sm"
                  data-date-format="mm/dd/yyyy"
                  id="end_date"
                  name="end_date"
                  required="false"
              />
            </div>
          </div>
          <div class="row">
            <div class="col-sm-2">
                <button class="btn btn-sm btn-primary" type="submit">Load Data</button>
            </div>
        </div>
    </form>
    {{ sum_2021|safe }}
    {% autoescape off %}
    {{ plt_div }}
    {% endautoescape %}
</main>
</div>
{% endblock %}

templates/expense_tracking/edit_expense.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Expenses{% endblock %}
{% block body %}
  <main>
    <legend class="border-bottom mb-4">
        Edit Expense
    </legend>
    <div class="container">
      <form method="POST">
          {% csrf_token %}
          {% if expense_to_edit %}
          <div class="form-group">
            <div class="row">
              <div class="col-sm-3">
                <label for="expense_date">Expense Date</label>
                <input
                    type="date"
                    class="form-control form-control-sm"
                    data-date-format="mm/dd/yyyy"
                    id="expense_date"
                    name="expense_date"
                    value='{{ expense_to_edit.expense_date|date:"Y-m-d" }}'
                />
              </div>
              <div class="col-sm-6">
                <label for="expense_type">Expense Type</label>
                <select
                  class="form-control form-control-sm"
                  id="expense_type"
                  name="expense_type"
                >
                  <option
                    selected="true"
                    value='{{ expense_to_edit.expense_type.pk }}'
                  >
                    {{ expense_to_edit.expense_type }}
                  </option>
                  {% for expense_type in expense_types %}
                    <option value="{{ expense_type.id }}">
                      {{ expense_type.name }}
                    </option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-sm-3">
                <label for="amount">Amount</label>
                <input
                  type="number"
                  step='.01'
                  class="form-control form-control-sm"
                  id="amount"
                  required="true"
                  name="amount"
                  value='{{ expense_to_edit.amount }}'
                />
              </div>
          </div>
            <div class="row">
              <div class="col-sm-6">
                <label for="name">Expense</label>
                <input
                  type="text"
                  class="form-control form-control-sm"
                  id="name"
                  name="name"
                  required="true"
                  value='{{ expense_to_edit.name }}'
                />
              </div>
              <div class="col-sm-6">
                <label for="org">Organization</label>
                <input
                  type="text"
                  class="form-control form-control-sm"
                  id="org"
                  name="org"
                  required="true"
                  value='{{ expense_to_edit.org }}'
                />
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
              <label for="notes">Notes</label>
              <input
                type="text"
                class="form-control form-control-sm"
                id="notes"
                name="notes"
                value='{{ expense_to_edit.notes }}'
              />
            </div>
            </div>
          <br />
          <div class="row">
            <div class="col-sm-3">
              <button
                class="btn btn-sm btn-primary"
                id="send_btn"
                type="submit"
                >
                  Update
              </button>
              <button
                onclick="javascript:history.back();"
                class="btn btn-secondary btn-sm"
                type="submit"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
        {% endif %}
      </form>
    </div>
  </main>
{% endblock %}

templates/expense_tracking/expense.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Expenses{% endblock %}
{% block body %}
  <main >
    <legend class="border-bottom mb-4">
        Expense List
    </legend>
    <div class="container-fluid">
    <table  id="expenseTable" class="table table-sm table-hover table-responsive-sm table-bordered" width="100%">
      <thead class="alert-secondary">
        <tr>
          <th class="fit" style="width:5%">ID</th>
          <th class="fit" style="width:10%">Expense Date</th>
          <th class="fit" style="width:15%">Expense Type</th>
          <th class="fit" style="width:15%">Expense</th>
          <th class="fit" style="width:15%">Organization</th>
          <th class="fit" style="width:5%">Amount</th>
          <th class="fit" style="width:25%">Notes</th>
          <th class="fit" style="width:5%"></th>
          <th class="fit" style="width:5%"></th>
        </tr>
      </thead>
      <tbody>
        {% for expense in my_expenses %}
          <tr>
            <td class="fit" style="text-align: center">{{ expense.id }}</td>
            <td class="fit" style="text-align: center">{{ expense.expense_date|date:"m/d/Y" }}</td>
            <td class="fit" style="text-align: left>">{{ expense.expense_type }}</td>
            <td class="fit" style="text-align: left">{{ expense.name }}</td>
            <td class="fit" style="text-align: left">{{ expense.org }}</td>
            <td class="fit" style="text_align: center">$ {{ expense.amount }}</td>
            <td class="fit" style="text-align: left">{{ expense.notes }}</td>
            <td class="fit" style="text_align: center">
              <a
                href="{% url 'expense_tracking:edit_expense' expense.id %}"
                class="btn btn-secondary btn-sm"
              >
                Edit
            </a>
            </td>
            <td class="fit" style="text_align: center">
              <a
                id="conf_del"
                href="{% url 'expense_tracking:delete_expense' expense.id %}"
                class="btn btn-danger btn-sm"
                onclick="return confirmDelete()"
              >
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    <script>
        function confirmDelete(){
          var res = confirm('Are you sure you want to delete this record?');

          if(res) {
            return true;
          } else {
            return false;
          }
        }
    </script>
    <script>
      $(document).ready(function() {
          $('#expenseTable').DataTable( {
              order: [[0, 'desc']],
          } );
      } );
    </script>
  </main>
{% endblock %}

templates/expense_tracking/index.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block body %}
<div
  class="background-home"
  id="outer-div"
  style="background-image: url({% static 'expense_tracking/images/pexels-tima-miroshnichenko-6694543.jpg' %});"
>
</div>
{% endblock %}

templates/expense_tracking/login.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %} Login {% endblock %}
{% load widget_tweaks %}
{% block body %}
<main>
    <legend class="border-bottom mb-4">
       Login
    </legend>
    <div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <div class="row">
                <div class="col-sm-12">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" required=true>
              </div>
            </div>
            <div class="form-group">
              <div class="row">
                <div class="col-sm-12">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" required=true>
              </div>
            </div>
            <br />
            <div class="form-group">
              <div class="row">
                <div class="col-sm-4">
              {% render_field form.captcha%}
              </div>
            </div>
            <div class="row">
              <div class="col-sm-2">
                  <button class="btn btn-sm btn-primary" type="submit">Login</button>
              </div>
            </div>
        </form>
    </div>
    <div>
        If you do forgot your password, <a href="{% url 'expense_tracking:password_reset' %}"><strong>reset</strong></a> now.
    </div>
</main>
{% endblock %}

templates/expense_tracking/results.html
{% extends 'expense_tracking/layout.html' %}
{% load static %}
{% block title %}Data Results{% endblock %}
{%block body %}
<div class="container">
<main>
    <legend class="border-bottom mb4">
        Expense Data Overview ({{ start }} - {{ end }})
    </legend>
    {% if none %}
      <p class="no_records">{{none}}</p>
    {% else %}
      {{ grouped_df|safe }}
      {% autoescape off %}
      {{ plt_div }}
      {% endautoescape %}
    {% endif %}
</main>
</div>
{% endblock %}